maintainer        'Neo'
maintainer_email  'accounts@neo.com'
license           'MIT'
description       'Uses sprout to configure an OSX workstation for development'
long_description  'Uses sprout to configure an OSX workstation for development'
version           '0.1.0'
supports          'mac_os_x'

depends           'neo_workstation'
depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
